### ISSUE TITLE
Modal doesnt appear

### ISSUE THREAD

**Issue by julienkermarec** [learn-ionic/ionic-5-angular-9-app#1]
Hello,

I have tested the modal launch, the backdrop appear, but not the modal content.

What is the problem ?

**Comment by mariusbolik** [comment]
Hey, sorry for the delayed replay. This seems to be an Firefox Issue. I submitted an Bug Report to Ionic :)

**Comment by mariusbolik** [comment]
@julienkermarec Will be fixed in Version 5.0.5 :)
